### ISSUE TITLE
UMAP visualization

### ISSUE THREAD

**Issue by chrboku** [metgem/metgem#100]
Dear team

Thank you for the amazing software. 

I am having an issue with the UMAP network arrangement. It only works with administrator privileges. 
Is that expected behavior? 

Thank you
best regards, christoph

**Comment by n-elie** [comment]
Dear Christoph,

Thanks you for the bug report. This is not intended.
Do you have an error message?
Are you using Windows? Which version?

Nicolas

**Comment by chrboku** [comment]
Thank you for your quick reply

I do not get any message, the bar simply runs forever. 
I am using Win10 with the latest updates. Also MetGem I am using in its latest version

Thank you!

**Comment by n-elie** [comment]
Could you please attach the log files generated by MetGem?
From MetGem, use the `Settings > Open user's folder` and navigate to the log folder. You should find a file named `MetGem.log`

**Comment by chrboku** [comment]
The file is empty. Attached is a screenshot though

![2022-03-11 14_58_11-Process File](https://user-images.githubusercontent.com/18591761/157881954-bba94a8e-b91e-4595-8e72-4828982dacf3.png)

**Comment by n-elie** [comment]
I made some tests and I was able to load UMAP module with MetGem 1.3.6 on my Win10 computer whether as admin or normal user.
Did you try to wait for one minute or two? UMAP is very long to load library. That's why it's loading was delayed to whenever it is needed to speed up initial loading of application.
