### ISSUE TITLE
"no module" for PHATE visualisation

### ISSUE THREAD

**Issue by simremy** [metgem/metgem#91]
Hi Nicolas,

In nightly 20719f, I cannot build a PHATE visualisation neither on windows nor on OSX
The "module" seems to be absent.

Take care
Simon

**Comment by n-elie** [comment]
Fixed by b9f7a21563187a513fa76c92e5362e9eb825ca00 and 5530a6ae57eea99d89a57b2814a1975e7c02f171.
Phate depends on scprep (KrishnaswamyLab/scprep@7e0e4b34d90d2171513559ae38b0190e6f370433) package which depends [packaging](https://pypi.org/project/packaging/) module to run, but this was conflicting with the `packaging` directory in metgem source.
